
["Poor Golems Control Values"]
	#Debug Level: 0 = Off, 1 = Log, 2 = Chat+Log
	#Range: 0 ~ 2
	debugLevel = 0
	#golemChunkLimit: Maximum Iron Golems per Chunk.
	#Range: 1 ~ 32
	ironGolemChunkLimit = 4
	#Seconds Between Iron Drops
	#Range: 1 ~ 3600
	secondsBetweenIronDrops = 30
	#Min Iron Drop Amount Maximum
	#Range: 0 ~ 1
	MinIronDropAmount = 1
	#Max Iron Drop Amount Maximum
	#Range: 0 ~ 32
	MaxIronDropAmount = 9
	#Do Iron Golems Drop Ingots(1), Nuggets(2), or Blocks(3) of Iron?
	#Range: 1 ~ 3
	ironGolemDropMode = 1

