
["Costs and Cooldowns:"]
	#DEFAULT = 8
	"Self Propulsion Cost" = 8
	#DEFAULT = 600
	"Everchanging Skies Cooldown" = 600
	#DEFAULT = 200
	"Strike From Above Cooldown" = 200
	#DEFAULT = 40
	"Strike From Above Cost" = 40
	#DEFAULT = 30
	"Mind Bender Cost" = 30
	#DEFAULT = 70
	"Dark Age Cost" = 70
	#DEFAULT = 35
	"Molding Lands Cooldown" = 35
	#DEFAULT = 80
	"Lifebringer Cooldown" = 80
	#DEFAULT = 60
	"Beast Tamer Cost" = 60
	#DEFAULT = 35
	"Ghostly Steed Cost" = 35
	#DEFAULT = 10
	"Force of Wind Cost" = 10
	#DEFAULT = 80
	"Wild Aid Cooldown" = 80
	#DEFAULT = 50
	"Self Propulsion Cooldown" = 50
	#DEFAULT = 70
	"Force of Wind Cooldown" = 70
	#DEFAULT = 70
	"Everchanging Skies Cost" = 70
	#DEFAULT = 55
	"Molding Lands Cost" = 55
	#DEFAULT = 50
	"Mind Bender Cooldown" = 50
	#DEFAULT = 4000
	"Dark Age Cooldown" = 4000
	#DEFAULT = 20
	"Wild Aid Cost" = 20
	#DEFAULT = 60
	"Beast Tamer Cooldown" = 60
	#DEFAULT = 20
	"Withering Stench Cost" = 20
	#DEFAULT = 200
	"Ghostly Steed Cooldown" = 200
	#DEFAULT = 25
	"Lifebringer Cost" = 25
	#DEFAULT = 35
	"Withering Stench Cooldown" = 35

["Droprates: (0 is never drop, 20 is always drop)"]
	#DEFAULT = 1
	"Archaic Heart Droprate" = 1
	#DEFAULT = 3
	"Beating Heart Droprate" = 3
	#DEFAULT = 8
	"Sweet Heart Droprate" = 8

